# Generated by Django 4.0.1 on 2022-11-23 13:40

import Gallery.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(help_text='Post', upload_to=Gallery.models.photo_path_post, verbose_name='Post')),
                ('description', models.TextField(blank=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('uploaded_on', models.DateField(default=datetime.datetime(2022, 11, 23, 13, 40, 36, 664868, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
